### PR TITLE
 Modifications to compile with mingw32

### PR DESCRIPTION
**Pull request by GustavoBlaze**
Before it was not giving to compile with mingw32. Changes were required in some makefile lines and few changes to the project source code. And a compilation of the Boost librarian 1_64 was also required. Replaces some otclient-libs-mingw32 files and uploaded for everyone to download the updated libraries.

### CODE REVIEW

**Comment by conde2** [comment]
It looks good, but could you commit only the code about MinGW ?

**Comment by GustavoBlaze** [comment]
The commit about mingw is https://github.com/edubart/otclient/pull/850/commits/690c5538e740bb60c325ff427d82886c50d8b038

**Comment by Felipe1993** [comment]
awesome @GustavoBlaze 
regards from otland

**Comment by Felipe1993** [comment]
im stuck here simce yesterday could someone help me pls? im having errors at the end of compilation

**Comment by edubart** [comment]
Nowdays you should use mingw-w64 but I've done the required changes to compile on mingw32 on https://github.com/edubart/otclient/commit/aa19f45d94b48a364c5cb6951e3090b72838ecfc and https://github.com/edubart/otclient/commit/8309fee510a30cb335813d246080ae3a0858a889

**Comment by Felipe1993** [comment]
im still getting errors while i try to compile with codeblocks im still using mingw32
@edubart 
[img]https://i.imgur.com/cJfQTsK.png[/img]

**Pull request closed without merging**
