### PR TITLE
Slight fix of Tile::isLookPossible() function

### PR DESCRIPTION
**Pull request by 4drik**
You should see through things that are translucent.

### CODE REVIEW

**Comment by slavidodo** [comment]
I don't think so, I've checked the client and it only specifies the "unsight" flag which respects to block-projectile

**Comment by 4drik** [comment]
@slavidodo, you mean CipClient? In that case what function does the translucent option have?

**Comment by slavidodo** [comment]
In Field:
```csharp
// in objects loop
CachedUnsight |= Object.IsUnsight; // BlockProjectile
```

In WorldMapStorage:
```csharp
public bool IsLookPossible(int x, int y, int z) {
	FieldRenderInfo info = GetFieldInfo(x, y, z);
	info.UpdateRenderCache();
	return !info.CachedUnsight;
}
```

**Comment by 4drik** [comment]
I understand, then I close the topic.
BTW. I'm not sure if translucent attribute works at all.
I had to create a new separate attribute to achieve my goal.

**Pull request closed without merging**
