### PR TITLE
Add 'GameKeepUnawareTiles' feature.

### PR DESCRIPTION
**Pull request by Mignari**
Remove tiles that we are not aware anymore by default.

### CODE REVIEW

**Comment by TheSumm** [comment]
Great! Thank you.

**Comment by iryont** [comment]
The idea is good, but it's highly inefficient.

**Comment by hrsantiago** [comment]
You wont have a lot of tiles, cause it's cleaned every time the map position changes. The maximum amount of tiles is around 18 * 15 * 16 = 4320. However this will be really uncommon. Usually, floor 7 will be completely full and maybe 2 more floors with some tiles. I'd say ~500 tiles is a good average, which is not a huge loop to do for each step.

**Comment by iryont** [comment]
Unfortunately you are assuming that everyone uses a view of 18x14 tiles. In such case it will work just fine, but it's still an inefficient code for larger views.

**Comment by hrsantiago** [comment]
Yeah, but i guess this is the default so most people wont have issues with it. For those using larger views, they've changed the map aware range somewhere. At this same place they can simply disable this feature.

**Pull request merged**
