### PR TITLE
Fixed several messageModes for older protocols

### PR DESCRIPTION
**Pull request by zygzagZ**
Inconsistences between const.lua and const.h were causing several messagetypes not to work.
Introduced in commit 1ec3b65a3af0d0bbc68fb1763b019f348d68decb

### CODE REVIEW

**Comment by zygzagZ** [comment]
Fixes  #753

**Comment by brewsterl** [comment]
Nice! thanks

**Comment by zygzagZ** [comment]
I can see that there were pull requests earlier that fixed just these issues. Why didn't they get merged? Is otclient repo here dead?

**Comment by brewsterl** [comment]
It can be said that he is a little dead

**Comment by Fluppix** [comment]
Thank you man, even if I don't need it. It's nice to see someone is workin on such things.

**Comment by asamy** [comment]
Hi, thanks.

**Comment by conde2** [comment]
@theSumm please close the issues mentioned in this pull request

**Pull request merged**
