### PR TITLE
Add enhanced animations support for outfits/Fix issue #642

### PR DESCRIPTION
**Pull request by djseban**
Finally managed to do a little. Enjoy, folks ;)

### CODE REVIEW

**Comment by djseban** [comment]
Fixed backwards compatibility (Protocols without enhanced animations had only Idle outfit position) in commit https://github.com/edubart/otclient/pull/736/commits/db24490d18e170f2e90004d8fbad8fcc45956ff5

**Comment by diath** [comment]
Good job. It would be nice though if you could replace tabs with spaces in your changes to keep it consistent with the rest of the files you've modified. Also I don't think the cast to LightView * is necessary, you can simply pass nullptr.

**Comment by djseban** [comment]
@diath Done.

**Comment by totolol123** [comment]
Nice :+1:

**Comment by HeavenIsLost** [comment]
I did not review the code, but thanks for fixing that issue :+1: 

@Mignari

**Comment by djseban** [comment]
Small note to the function Creature::updateWalkAnimation. The thing is footDelay is, by default, set to getStepDuration(true) / 3, so basically animation speed is hardcoded for outfits with 3 animations - hence creatures walk in slow motion. I tried to fix it, but every way I tried I get visible "frameskips". If someone would be willing to fix this issue, it would be great.

**Comment by djseban** [comment]
I couldn't resist ;>

**Comment by conde2** [comment]
Does it break compatibility with other versions ?

**Comment by djseban** [comment]
@conde2 No. In fact all other versions are still compatible with new ThingType loading scheme. Old scheme for new outfits was just skipping FrameGroupIdle and loading only FrameGroupMoving, so I adjusted ThingType class to contain a vector of (new) FrameGroup class' objects', containing all the textures and properties of certain framegroup - so if you load a Thing (outfit), that has only one FrameGroup, then loading functions creates only one object of FrameGroup class, therefore it can still load it properly.

**Comment by edubart** [comment]
Don't change the code style of other unrelated code if you want it merged, makes hard to review and also diverges from the standard style.

**Comment by djseban** [comment]
@edubart Since I made a little mess with commits in this pull request, maybe I should create another containing all of changes/additions in the code?

**Comment by hrsantiago** [comment]
Yes, and only with the actual changes that matters.
Do not change stuff like if() to if ()
Pay attention to tabs and spaces. Otc uses 4 spaces

**Comment by diath** [comment]
It seems that this change breaks outfit image exportng. You can reproduce it by opening the client terminal (^T) and typing in the following:
```lua
g_things.getThingType(128, ThingCategoryCreature):exportImage('test.png')
```

Prior to applying this patch, this would export the outfit sprites into test.png, after applying the patch it does nothing. It seems that it does not pass this check in ThingType::exportImage function:
```c++
if (m_frameGroups[i]->m_spritesIndex.size() == 0) {
```

**Comment by belizariogr** [comment]
i found a bug... if you are near of a creature that have animations when is idle (like wyvern), you get a crash. Debuging, i found the wrong line.

`int ticksPerFrame = 1000 / getAnimationPhases();`

function getAnimationPhases() returns zero, and raise an error.

**Comment by belizariogr** [comment]
I managed the problem changing code a little bit...

`if (isAnimateAlways() && animateIdle) {
			type = FrameGroupMoving;
			int ticksPerFrame = 1000 / getAnimationPhases(type);
			animationPhase = (g_clock.millis() % (ticksPerFrame * getAnimationPhases(type))) / ticksPerFrame;`

`for (int yPattern = 0; yPattern < getNumPatternY(type); yPattern++) {`

**Comment by BARBA-N3GR4** [comment]
Belizario jr can pass me your creature.cpp ??

As he said above, Bat, Wyvern, Fire Elemental etc ... creatures that do not stop animation, makes the client crashing.

**Comment by belizariogr** [comment]
[creatures.zip](https://github.com/edubart/otclient/files/416713/creatures.zip)

**Comment by BARBA-N3GR4** [comment]
thank you dude, more is creature.cpp xD not creatures.cpp

in which you applied the fix

if (isAnimateAlways () && animateIdle) {type = FrameGroupMoving; ticksPerFrame int = 1000 / getAnimationPhases (type); animationPhase = (g_clock.millis ()% (* ticksPerFrame getAnimationPhases (type))) / ticksPerFrame;

  for (int yPattern = 0; yPattern <getNumPatternY (type); yPattern ++) {

**Comment by belizariogr** [comment]
ahhh.... sorry, my bad... 
[creature.zip](https://github.com/edubart/otclient/files/416722/creature.zip)

**Comment by BARBA-N3GR4** [comment]
Thanks man xD, 
It worked

**Comment by totolol123** [comment]
Any news?

**Comment by djseban** [comment]
@totolol123 Since I started uni this September (not related to programming) I pretty much don't have time to resolve issues in this PR or do any programming, so if any dev would be willing to fix these issues, feel free to do it, just give me credits if you'll start from my work. If no one takes this case, then most likely I will start to work on it on spring break.

**Comment by Crownn** [comment]
when you walk with spells like "utani hur" the speed of the animation its more faster than the needed to walk :/

**Pull request closed without merging**
