### PR TITLE
Added new health bar styles

### PR DESCRIPTION
**Pull request by Ceetros**

### CODE REVIEW

**Comment by diath** [comment]
This is inefficient, the texture will be loaded with every frame drawn, you should store it as a class member.

**Comment by hrsantiago** [comment]
And also should follow the example of skull/emblems/shields to set the filename

**Comment by Ceetros** [comment]
Yeah, im updating this, a momment :)

**Comment by EgzoT** [comment]
I think better way is modify this to choose type of healthbar style in lua:

- Without image (old style)

- With image (new style)

**Comment by Riverlance** [comment]
I tried it here, and it lags too much.
The drawInformation function executes too much times and quickly, so **your FPS will decrease significantly**.

My solution here was to create the texture as a creature variable, not as you done inside the drawInformation.

At `Creature::Creature()`, you add like this:
``` C++
m_creatureBarTexture = g_textures.getTexture("/images/game/lifebar/background");
```

Now you are free to use this texture on drawInformation without lag.

**Pull request closed without merging**
