### PR TITLE
Option for loading data/modules/init.lua from encrypted zip

### PR DESCRIPTION
**Pull request by Source61**
Otclient can now load data/modules/init.lua from data.zip and modules.zip by setting the preprocessor ZIPENCRYPTION.
The zips must be encrypted with ZipCrypto, not AES.
Default password m_zipPassword = "12345678" and is set in src/framework/core/resourcemanager.h.
Init.lua must be included in either data.zip or modules.zip.

To create encrypted zips:
1. Install 7-zip
2. Copy init.lua into data
3. Go into data
4. Select all, right click, 7-zip, Add to archive...
5. Set password and ZipCrypto as encryption method
6. Repeat for modules directory

Credits to Zelek. Paid him $18 for this 8 months ago.

### CODE REVIEW

**Comment by ralke23** [comment]
very nice feature! thanks

**Review by marmichalski — COMMENTED** [review]
Well, this is bad and not even worth that $18 you paid in mid-late 2020. I don't even know why this should be included in the README.

**Comment by Source61** [comment]
> Well, this is bad and not even worth that $18 you paid in mid-late 2020. I don't even know why this should be included in the README.

Hate it or love it, it's the first publicly available encryption for otclient (and it's been 8 years btw, maybe time to look at the community instead of hating on contributors sharing things for free?), it's easy to implement for people with their own forks and easy to use, I shared it for free, and I'm sure it's better than nothing, feel free to prove me wrong with some kind of a text or video tutorial describing step by step how to easily break it if I'm wrong.
PS: Looking at strings doesn't count as you're intended to obfuscate the key string as much as possible (easy to do) to avoid the key being easily retrieved. I'll accept any other method though.
Also if you have something better feel free to share yours with the community :)

The readme update was intended only for my fork. I assume it can be ignored/excluded when merging, if I'm wrong and a maintainer would otherwise like to accept the pr then they can let me know and I'll revert the changes to the readme temporarily.

**Comment by diath** [comment]
> PS: Looking at strings doesn't count as you're intended to obfuscate the key string as much as possible (easy to do) to avoid the key being easily retrieved.

Instead you can just set a breakpoint on the read method when the client did all the password deobfuscation for you and read it from there.

**Comment by Source61** [comment]
> 
> 
> > PS: Looking at strings doesn't count as you're intended to obfuscate the key string as much as possible (easy to do) to avoid the key being easily retrieved.
> 
> Instead you can just set a breakpoint on the read method when the client did all the password deobfuscation for you and read it from there.

Congratulations you've just described the process of cracking virtually any encrypted software using dynamic tools without actually saying or evaluating anything as requested which btw wasn't even for you.

Do you have any relevant objections to the PR?

**Comment by diath** [comment]
> Do you have any relevant objections to the PR?

Yes, it's shit.

**Comment by Source61** [comment]
Good job Diath. I read posts by you many years ago where you talked about mod corruption on OTLand, nowadays you're just the same if not worse than the rest of them, just trying to fuck over the community any way you can by gatekeeping and providing either no justification or completely bogus justifications for things you do, like incorrectly labeling issues as duplicates when clearly not applicable, and the bogus justification "we're not gonna use newer C++ standards after C++11", why?, "no reason, we're just not going to because I said so".
You and Iryont are honestly doing such a shitty job that even OTLand themselves which everyone knows are corrupt had to create their own OTClient repo to get anything done...
So congratz not only on being a shitty developer but a shitty human being as well.
Cheers.

**Comment by diath** [comment]
> completely bogus justifications for things you do

Because I did not feel like I need to elaborate further on this PR since you made it obvious that you know these things yourself but here it goes:
* As you know, client-sided encryption is reversible, so the only factor here is making things as obfuscated as possible while adding many layers of obfuscation to deter people from doing it through the sheer amount of time investment required, if the method of obfuscation is public, then the obfuscation is as good as having no obfuscation at all. If I merged this change, I (or anyone else), could just post a 3 step tutorial to reverse it 5 minutes later.
* Because adding modules encryption to the base project goes against the spirit of the open source project itself, if you want to make such change in your own project, and the license permits you to, feel free to do it, but do it at your own discretion, or post a tutorial elsewhere, but I feel like such things have no place in the base client repository.

> like incorrectly labeling issues as duplicates when clearly not applicable,

Because you described the issue exactly as another issue, without elaborating further, while withholding a patch for an issue that you had a fix for. Keep misreporting issues, and I will keep mislabeling them.

> and the bogus justification for not fixing OTC compilation out of the box "we're not gonna use newer C++ standards after C++11", why?, "no reason, we're just not going to because I said so, because I'm a big asshole that does whatever I want and don't give a fuck about anyone else than myself".

Focus on the actual reason, which was that the issue is with the build system providing the compiler with the wrong include paths and not the source code itself. Provide a proper patch and not a workaround and I will gladly merge it. Additionally your reasoning was that just because your specific version of the compiler supports the `__has_include` directive when building with the C++11 standard that we should ignore the fact that it's technically not standard compliant (the feature is available since C++17), oh and by the way you'll be happy to hear that the client now uses C++14 by default.

> You and Iryont are honestly doing such a shitty job that even OTLand themselves which everyone knows are corrupt had to create their own OTClient repo to get anything done...
> So congratz not only on being a shitty developer but a shitty human being as well.

If contributing back every single fix to an issue I've encountered while using OTC as a base client myself and maintaining the repository makes me both a shitty developer and shitty human being, then I'm glad to be both.

**Comment by Source61** [comment]
> > completely bogus justifications for things you do
> 
> Because I did not feel like I need to elaborate further on this PR since you made it obvious that you know these things yourself but here it goes:
> 
>     * As you know, client-sided encryption is reversible, so the only factor here is making things as obfuscated as possible while adding many layers of obfuscation to deter people from doing it through the sheer amount of time investment required, if the method of obfuscation is public, then the obfuscation is as good as having no obfuscation at all. If I merged this change, I (or anyone else), could just post a 3 step tutorial to reverse it 5 minutes later.

There is no public obfuscation involved in this PR, it's just the encryption. The obfuscation is up to the user like I said in the comment that you quoted in your first comment, and which you agreed to here...
Without pretending to be an expert at cracking (I know the basics which should be sufficient to have a conversation with me on instead of just saying "it's shit" and close the PR, wtf is that kind of behavior?), I disagree that anyone could post a 3 step tutorial after to reverse it. You'll need to find the correct bp and know a bit about ASM and debugging to actually finish the deal.
Afaik the sad reality is that there are only so many read functions anyway, so using this exact same process anyone can reverse all forms of OTClient decryption unless they create their own reading functions, and actually even that can be bypassed easily.
So yes, no form of client-based encryption is secure on its own, but neither are IRL doors or locks, they can very easily be broken down with physical force, but tell me does that mean you don't lock your door at night?
The point is some security is always better than no security, and especially in a software community it will get people talking about it. Currently there is literally 0 instructions, tutorials, information or even **discussion** about using encryption or any other form of protection with OTClient.
 
>     * Because adding modules encryption to the base project goes against the spirit of the open source project itself, if you want to make such change in your own project, and the license permits you to, feel free to do it, but do it at your own discretion, or post a tutorial elsewhere, but I feel like such things have no place in the base client repository.

Why not? You think this same standard should apply to Open Tibia Servers and Websites? That if it's used/hosted, then it should be mandatory to continuously release the sources of this software to the public? Maybe it should also be mandatory to share our computers with other people who wants it because we want to be "open source", so everyone are entitled to take (steal) what they want from other people and make money off it, this is your philosophy?

Btw it's also ironic you wanna complain about using encryption, but you think it's perfectly fine to have builtin spyware in this game client that sends whatever data the developer wants to their website about the client machine, to you this is in spirit with this open source project?
> 
> > like incorrectly labeling issues as duplicates when clearly not applicable,
> 
> Because you described the issue exactly as another issue, without elaborating further, while withholding a patch for an issue that you had a fix for. Keep misreporting issues, and I will keep mislabeling them.

Not only is your logic shit here because you've already mislabeled and given bogus answers two times before, a third time now by just saying "it's shit" instead of saying anything productive, when this is my first time reporting about these problematic behaviors of yours or anything else in this repo or anything that relates to you.
But your facts are also shit, because I did not misreport anything. If you compare the issues they are literally miles apart. Yes I'm withholding the patch because I don't live in Soviet Russia and I'm not required to give away everything I own and everything I do because someone else wants it.
I offered to release the patch for the price I paid for it, I'm trying to be fair and release useful things within reason, but I'm not going to be anyone's sugar daddy, especially not for a corrupt community/staff that already only cares about money, status and controlling other people.
> > and the bogus justification for not fixing OTC compilation out of the box "we're not gonna use newer C++ standards after C++11", why?, "no reason, we're just not going to because I said so, because I'm a big asshole that does whatever I want and don't give a fuck about anyone else than myself".
> 
> Focus on the actual reason, which was that the issue is with the build system providing the compiler with the wrong include paths and not the source code itself. Provide a proper patch and not a workaround and I will gladly merge it. Additionally your reasoning was that just because your specific version of the compiler supports the `__has_include` directive when building with the C++11 standard that we should ignore the fact that it's technically not standard compliant (the feature is available since C++17)

It doesn't matter, probably about 99% of OTClient compilations are done on and for Windows and it makes no sense to leave the software broken by default for literally years at a time because "you're not a fan of any workarounds whatsoever", even if they are tiny and insignificant.

On the second point, yes, everyone should use a relatively modern compiler, we should not provide gcc compatibility for someone that runs Windows 95.
You never mentioned that it's technically not standard compliant, if that's the justification then fair enough.
I would've still used the workaround and only considered reverting it if people started complaining assuming anyone would have any issues with it which I kinda doubt, but personally I believe in being a little bit practical, maybe you don't, either way I'm fine with that particular justification which you forgot to actually mention in the issue.

> oh and by the way you'll be happy to hear that the client now uses C++14 by default.

Ok. Doesn't really matter to me especially when one of the next things you're going to do after I guess I made you reconsider using a newer gcc version is tell me that my PR is shit without further or prior explanation?
I don't personally get anything from having OTClient use C++14 or C++17, I was just trying to contribute and solve problems.

> > You and Iryont are honestly doing such a shitty job that even OTLand themselves which everyone knows are corrupt had to create their own OTClient repo to get anything done...
> > So congratz not only on being a shitty developer but a shitty human being as well.
> 
> If contributing back every single fix to an issue I've encountered while using OTC as a base client myself and maintaining the repository makes me both a shitty developer and shitty human being, then I'm glad to be both.

Ok, so I guess you've encountered 41 issues in the past 7 years which is when you made your first commit, most of which are like a couple of lines of Lua code?
I noticed even your latest commits are usually 1-3 lines and often isn't even any code.
Haven't looked at all your commits, but looks like you have at least one huge commit, however it looks like >90% of it is literally you using the replace function in your text editor to fix purely esthetics things like replacing size() == 0 with empty() and replacing NULL with nullptr?
Also you've been a maintainer for what, 3-4 years, and probably accepted like 50 PRs yourself?
Is that all it takes for you to feel great about yourself and ignore everything else you ever do?

**Comment by diath** [comment]
If you're not satisfied with the current direction of the client nor the current maintainers, feel free to reach out to edubart who is still the owner of this repository. I'll happily pass you the torch.

**Comment by Source61** [comment]
I think you're missing the point. I'm trying to appeal to your sense of reason, but maybe that's my mistake for assuming you have any to begin with.
I wouldn't mind if you left at this point, but it's not my goal to make you leave or to have edubart appoint me, my goal is just to have someone reasonable and competent maintain it that doesn't (intentionally???) mislabel issues, allow the software to stay broken out of box for years even though there's a simple and tiny workaround for it (forcing >99% of the users of the software to have to continue to add and remove all the different #include's everytime they want to do one cycle of compiling client -> updating/pulling/pushing repo), randomly call PR's "shit" out of nowhere without further or prior explanation, etc, these are the actions of someone I have to question the sanity of.

Also your last statement makes no sense, you might as well be saying "I'll happily do what you want if you call the cops and get them to physically coerce me to do what you want me to do", only this cop has been virtually retired from his job for the last 7 years...

**Comment by Source61** [comment]
Have you considered going back to OTLand to suck staff or some other powerful men off irl in return for favors, maybe you could work your way up to suck Putin off someday?
I honestly really think this kind of work would suit you well, and if you think about it you wouldn't even have to post 3 lines of code every third month.

**Pull request closed without merging**
