### PR TITLE
Fixed some old typos.

### PR DESCRIPTION
**Pull request by zeeb92**
These typos has been around for a few years now, it's a commonly asked question on how to solve it so let's just add it to the master already.

### CODE REVIEW

**Comment by marmichalski** [comment]
Not a typo.

**Comment by diath** [comment]
As discussed here <https://github.com/edubart/otclient/pull/1111#issuecomment-695783454>, this needs to be fixed in the VS solution and not in the codebase.

**Comment by marmichalski** [comment]
@zeeb92 see if #1174 helps in your case. 🥲

**Comment by zeeb92** [comment]
I see.
Alright, I'm closing it then.

**Pull request closed without merging**
