### PR TITLE
Initial port to mobile devices

### PR DESCRIPTION
**Pull request by Tulioh**
Has some things that need to be made, that is:
- Fix input events on SDL.
- Recreate the UI using the same code that desktop uses for code reuse (obvious).
- Fix a bug that occur on login when the first packs is received (maybe the merge fix this)

### CODE REVIEW

**Comment by iryont** [comment]
Are you still having problem with black screen? Are you sure the SDL2 is initialized correctly? It would be wise to create a Window on your Linux platform and check it out.

**Comment by Tulioh** [comment]
This bug was fixed. This commit that you are seeing is old. Look the lasted
commits.


2015-02-07 18:54 GMT-02:00 Konrad Kuśnierz <notifications@github.com>:

**Comment by iryont** [comment]
Indeed, I did compile it and it works just fine. However, there is plenty of work - would be cool to change the viewport to resize frame buffer into better fitting resolution (e.g. 2560 x 1600 => 640 x 400). I did that before in another mobile port. Also, the OpenGL context has to be reinitialized with new dimensions once you change the orientation. I haven't tried logging in since it's impossible to click anything (LG G3, 2560 x 1600) so fixing the viewport would be cool. I will definitely have some fun with it :)

**Comment by Codinablack** [comment]
OMG! REVOLUTION!!!!!!!!!!!!!!!!

Hell yeah guys! This is what I am talking about, so glad to see some people with the ability working on implementing this!

**Comment by BenDol** [comment]
:+1:

**Comment by Nu77** [comment]
cool :)

**Comment by rowaraujo** [comment]
REVOLUTION!!!

**Comment by comedinha** [comment]
lol :+1:

**Comment by dominique120** [comment]
I went through all the steps mentioned by @Tulioh and everything in between. I compiled OTC and made an APK. Ant was complaining about some resource problem so I fixed by creating a file called *strings.xml* in *otclient/android/project/res/values* with the following contents:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">"otc"</string>
</resources>
```
However once I installed the APK with adb and try to launch it in android it crashes telling me "unfortunately, otc has stopped"

I tried using a debugger but I dont really know how to. However I managed to get [this](http://pastebin.com/u7SpMKWd) from DDMS. That part of the log starts when I press on the application and ends roughly right after I press ok on "unfortunately otc has stopped...". I tried it on a Galaxy Tab 4 and Galaxy Core 2(The log is from the tab).

I hope this helps and I hope you continue working with this, it is a great first step in the right direction.

**Comment by Tulioh** [comment]
Hello @dominique120, your problem is that the apk had not been compiled, or something else, because the main error in your log is: "04-22 22:15:27.997: E/AndroidRuntime(12916): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.libsdl.app.SDLActivity" on path: DexPathList[[zip file "/data/app/org.libsdl.app-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.libsdl.app-1, /vendor/lib, /system/lib]]".
Run "ant debug" again on the project folder and see if you will get "BUILD SUCCESS".

**Comment by dominique120** [comment]
[Here](http://pastebin.com/jJjv5Ad1) is the output of `ant clean` `ant debug` and `adb install -r OTClientMob-debug.apk`

I have been doing this work on Fedora 20 x32

**Comment by Tulioh** [comment]
Try to change the sdk version on AndroidManisfest.xml to your phone version.
Em 23/04/2015 12:45, "Dominique Verellen" <notifications@github.com>
escreveu:

**Comment by iryont** [comment]
@Tulioh 

Did you fix the XTEA encryption? AFAIR it did not work properly.

**Comment by Tulioh** [comment]
Not, because I'm only porting to mobile.

**Comment by dominique120** [comment]
I tried changing the target version to 19(for my device) in android xml and then executing ant and adb but it still crashes.

Then I changed the sdk version on the cmake command and repeated the steps(with the sdk version changed where it must be) but it still crashes.

**Comment by Tulioh** [comment]
Check on you final apk that the SDLActivity.class exists

**Comment by dominique120** [comment]
I'm not really sure how to do that(I tried using some program called apk analyzer) so I have uploaded the apk that was generated.

http://www.mediafire.com/download/ebvvdagnzkz7yyw/OTClientMob-debug.apk

**Comment by Tulioh** [comment]
I had made a mistake (sorry), just clone my current repository and try again.

**Comment by Tulioh** [comment]
One more thing, add the "libSDL2.so" on the android/project/libs/armeabi-v7a folder

**Comment by dominique120** [comment]
It compiled and it no longer crashes. But when I start it I see only a black screen. Is this the bug that @iryont mentioned?

**Comment by dominique120** [comment]
Here is a log like the other one I posted above: http://pastebin.com/MLC5UB8T

**Comment by Tulioh** [comment]
Did you put these folders and files: data, modules, init.lua and otclientrc.lua inside the /sdcard/OTClient folder?

**Comment by dominique120** [comment]
Yes I have an OTClient folder with all the normal contents in my SD card but its still not working.
However I think my SD card is mounted in /storage/extSdCard, I dont know if that makes a difference or not

**Comment by Tulioh** [comment]
This is the problem :/. The code is searching on "/sdcard/OTClient/". But to you compile and test the OTClient Mobile, change your sdcard location on "src/framework/core/resourcemanager.cpp".

**Comment by dominique120** [comment]
Instead of recompiling everything I just copied my otclient folder to /sdcard and now it works!

img

**Comment by Tulioh** [comment]
:+1:

**Comment by BenDol** [comment]
Next step is to create mobile widgets that will be used to make the display easier to use :)

**Comment by iryont** [comment]
The current UI is not DPI aware and is completely useless on mobile devices. As for the start it would be cool to have TrueType fonts renderer.

**Comment by dominique120** [comment]
I think it would be a good idea to make a list of of tasks that need to be completed. 

Dominique Verellen

**Comment by Tulioh** [comment]
Yeah! I think too

**Comment by dominique120** [comment]
Well you're the expert so you should start it :p

Dominique Verellen

**Comment by Tulioh** [comment]
Check the README of my fork, and update if necessary.

**Comment by BenDol** [comment]
Should this be merged into an new branch on edubart/otclient? Or are you happy to keep maintaining this branch of the project on your fork @Tulioh?

**Comment by Tulioh** [comment]
Create a new branch on edubart ;)

**Comment by BenDol** [comment]
@Tulioh if you aren't an otclient collaborator you will be soon so you can commit to the https://github.com/edubart/otclient/tree/mobile_port branch.

**Pull request closed without merging**
