### PR TITLE
Improved Docker support

### PR DESCRIPTION
**Pull request by f0rmiga**
- Fixed Dockerfile syntax.
- Consolidated dependencies installation.
- Removed unneeded dependencies.
- Unwrapped single-line commands into multi-lines for better caching and readability.
- Added `strip` step for the final otclient binary.
- Used multi-stage Docker building for better final image sizing.
- Pinned the base image to a specific hash to avoid undesired changes to the `latest` tag.
- Removed build.sh and run.sh (these files didn't make sense).
- Updated README.md to reflect the changes.

### CODE REVIEW

**Comment by diath** [comment]
You could set [CMAKE_INSTALL_PREFIX ](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html) for the PhysFS project so that the install target installs the dynamic file in the desired location instead of moving the file manually. Also you could use [nproc ](http://man7.org/linux/man-pages/man1/nproc.1.html) instead of grepping procfs.

**Comment by f0rmiga** [comment]
@diath Thanks for catching those. For the `mv`, it was plain copy-pasta leftover from the previous code. We actually don't need to change its location.

**Comment by f0rmiga** [comment]
@diath Sorry for last-minute changes to CI. Let's see how it goes now.

**Comment by iryont** [comment]
Good job.

**Comment by midacts** [comment]
The docker build is just for the linux otclient, right?

**Comment by diath** [comment]
That's correct.

**Pull request merged**
