### PR TITLE
Update Visual Studio Project

### LINKED ISSUE #795: Link Download die msvc2013
https://www.dropbox.com/sh/se1okacemoqzjve/dI4ODbq7OT/otclient-msvc13-libs.zip

### PR DESCRIPTION
**Pull request by conde2**
Update Visual Studio to work with PATH system variables in Windows
systems. Credits go to @Radseq for changing the project and to me for
update to Visual Studio 2015

Closes
#795
#746
#718
#724
#713

### CODE REVIEW

**Comment by conde2** [comment]
@asamy, @brunominervino

Please test and report any problem

**Comment by brunominervino** [comment]
@conde2 I have tested with registrations and don't work.

Registering manually, works perfect (just some warnings). I have made pull requests in your repositories, my idea is keep using old structure.

Thank you very much!

**Comment by conde2** [comment]
It does work, you need to close Visual Studio before registering PATH variables

**Comment by brunominervino** [comment]
I know man, I have registered the PATH variables before open VS.
According my experience with forgottenserver, many peoples have problem with reg.bat (even though it is easier). This is only an idea.

Your work is already amazing.

**Comment by conde2** [comment]
Thank you. Can you check if running the script in Admin mode fix the problem ? Also could you check your Path variables ? If there is a problem we can write down a troubleshooting section in WIKI

**Comment by brunominervino** [comment]
I registered running reg.bat with Admin Mode. Maybe I can test again with my personal computer (just at night).

**Comment by conde2** [comment]
I will close this pull request to split commits

**Pull request closed without merging**
